### ISSUE TITLE
Graph issue when direct effect is negative

### ISSUE THREAD

**Issue by ozak** [damiancclarke/plausexog#2]
Hi Damian,

I noticed that if one tries to generate a plot with the direct effect being negative  it seems to fail. Any idea why? Here's an example based on the example in the help (btw the ``webuse`` command fails, I guess the ``dta`` file is not there anymore)

    reg net_tfa `xvar' p401  e401, vce(robust)
    mat A= e(V)
    local d = _b[e401]
    local gammay = _b[e401]+2*sqrt(A[19,19])
    local gammayb = _b[e401]-2*sqrt(A[19,19])
    plausexog uci net_tfa `xvar' (p401 = e401), gmin(-10000) gmax(10000) grid(2) level(.95) vce(robust) graph(p401) graphopts(xline(`d') yline(0, lcolor(blue) lpattern(dot) lwidth(.5)) )

This should put a red line at the estimated effect from the horse race. But the plot does not even show the region with negative effects. 

![image](https://cloud.githubusercontent.com/assets/650534/21056482/6b623f6a-bdfb-11e6-97ec-66af538981ad.png)

If instead one runs

    plausexog uci net_tfa `xvar' (p401 = e401), gmin(`gammayb') gmax(`gammay') grid(2) level(.95) vce(robust) graph(p401) graphopts(xline(`d') yline(0, lcolor(blue) lpattern(dot) lwidth(.5)) )

then the plot does not include the full region with the 95% interval around the estimated direct effect from the OLS. 

![image](https://cloud.githubusercontent.com/assets/650534/21056704/63aaab58-bdfc-11e6-9984-2892f0b4a7e7.png)

Even worse, although the estimated ``gamma=-2129.7533`` in OLS, the graph puts the red line in the wrong place completely.

If instead one focuses on a variable that has a positive direct effect in the OLS, then the plot works correctly. E.g., 

    reg net_tfa `xvar' p401  e401, vce(robust)
    mat A= e(V)
    local d = _b[marr]
    local gammay = _b[marr]+2*sqrt(A[13,13])
    local gammayb = _b[marr]-2*sqrt(A[13,13])
    plausexog uci net_tfa `xvar' (p401 = e401), gmin(-10000) gmax(10000) grid(2) level(.95) vce(robust) graph(marr) graphopts(xline(`d') yline(0, lcolor(blue) lpattern(dot) lwidth(.5)) )

![image](https://cloud.githubusercontent.com/assets/650534/21056433/3962ba08-bdfb-11e6-98b2-e5217583c9bf.png)

    plausexog uci net_tfa `xvar' (p401 = e401), gmin(`gammayb') gmax(`gammay') grid(2) level(.95) vce(robust) graph(marr) graphopts(xline(`d') yline(0, lcolor(blue) lpattern(dot) lwidth(.5)) )

![image](https://cloud.githubusercontent.com/assets/650534/21056389/038957d4-bdfb-11e6-9f6f-6fd9d6013852.png)

**Comment by damiancclarke** [comment]
Hi Ömer  (@ozak),

Thanks for finding this bug.  I have identified the bug, and as you suggest, the bug was affecting graphical output for the UCI case when the range of gammas overlapped zero.  It had no implications for estimated values of bounds reported and returned by the ado in output for the UCI case (even when overlapping zeros), or in graphs where the gammas were universally positive or negative.

The code has been updated and now works for UCI graphs even when graphing over a range of values overlapping zero.  For example, the output to your first identified code is provided below:
```
reg net_tfa `xvar' p401  e401, vce(robust)
mat A= e(V)
local d = _b[e401]
local gammay = _b[e401]+2*sqrt(A[19,19])
local gammayb = _b[e401]-2*sqrt(A[19,19])
plausexog uci net_tfa `xvar' (p401 = e401), gmin(-10000) gmax(10000) grid(2) level(.95) vce(robust) graph(p401) graphopts(xline(`d') yline(0, lcolor(blue) lpattern(dot) lwidth(.5)) )
```
![bug2](https://cloud.githubusercontent.com/assets/6189574/21297521/a4f7c27e-c560-11e6-9cbe-6db7b5874573.png)

Here values on the x-axis to the right of zero refer to bounds when assuming that gamma is distributed as U(0,delta), and to the left of zero refers to bounds when assuming that gamma is distributed as U(delta,0).

Thanks again for the report and helping correct the ado.
